name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: Build wasm
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall -y --no-symlinks wasm-bindgen-cli

      - name: Generate wasm bindings
        run: wasm-bindgen target/wasm32-unknown-unknown/release/sing_dae.wasm --out-dir wasm-pkg --target web

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          working_directory: wasm-pkg
          files: |
            sing*
